apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kmwrvwav1-python-gitops
  description: This is GitOps manifest for kmwrvwav1-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=kmwrvwav1-python
    backstage.io/kubernetes-id: kmwrvwav1-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: kmwrvwav1-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kmwrvwav1-python
